### ISSUE TITLE
ImportError: cannot import name WavPackDecoder

### ISSUE THREAD

**Issue by aplsms** [tuffy/python-audio-tools#66]
I've install audiotools on the MacOs.
`Darwin gamma.apl 14.5.0 Darwin Kernel Version 14.5.0: Thu Apr 21 20:40:54 PDT 2016; root:xnu-2782.50.3~1/RELEASE_X86_64 x86_64 (Yosemite)`

and got error with .wv file:

```
$ tracksplit --cue May\ 1968.cue May\ 1968.wv -t flac -q 1 -j 4
Traceback (most recent call last):
  File "/usr/local/bin/tracksplit", line 529, in <module>
    queue.run(options.max_processes))
  File "/usr/local/lib/python2.7/site-packages/audiotools/__init__.py", line 5493, in run
    return self.__run_parallel__(max_processes=max_processes)
  File "/usr/local/lib/python2.7/site-packages/audiotools/__init__.py", line 5681, in __run_parallel__
    raise self.__raised_exception__
ImportError: cannot import name WavPackDecoder
```

how can i solve it?

**Comment by willtang** [comment]
The error is that WavPack library couldn't be found in the system during audiotools setup. You could use Homebrew to install the library like that: `brew install wavpack`.

Afterward just build and setup audiotools again and Voila!

**Comment by pa167** [comment]
Ver todo
