### ISSUE TITLE
raise UnsupportedFile(filename)

### ISSUE THREAD

**Issue by heavytull** [tuffy/python-audio-tools#75]
Very often when trying to open a file with supported format like mp3, audiotools output this error:

    file01 = atls.open("file.mp3")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site-packages/audiotools/__init__.py", line 1780, in open
        raise UnsupportedFile(filename)
    audiotools.UnsupportedFile: file.mp3

I have not found any clew by looking at the tag info.

**Comment by laurentparmentier** [comment]
Did you get anywhere with this issue? Having the same problem

**Comment by heavytull** [comment]
not at all
